<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Magento\Catalog\Helper\Data as CatalogHelper;
use Magento\Catalog\ViewModel\Product\Breadcrumbs;
use Magento\Framework\Json\Helper\Data;
use Magento\Theme\Block\Html\Breadcrumbs as BreadcrumbsBlock;
use Opengento\ProductBreadcrumbs\ViewModel\Product\Breadcrumbs as BreadcrumbsConfig;

/** @var BreadcrumbsBlock $block */

/** @var Breadcrumbs $viewModel */
$viewModel = $block->getData('viewModel');
/** @var BreadcrumbsConfig $config */
$config = $block->getData('breadcrumbsConfig');
?>
<?php if ($config->isServerSideRendered()): ?>
    <?php
    /** @var CatalogHelper $catalogHelper */
    $catalogHelper = $this->helper(CatalogHelper::class);
    /** @var BreadcrumbsBlock $breadcrumbs */
    $breadcrumbs = $block->getLayout()->createBlock(BreadcrumbsBlock::class);
    $breadcrumbs->addCrumb(
        'home',
        [
            'label' => __('Home'),
            'title' => __('Go to Home Page'),
            'link' => $block->getBaseUrl()
        ]
    );
    foreach ($catalogHelper->getBreadcrumbPath() as $name => $crumb) {
        $breadcrumbs->addCrumb($name, $crumb);
    }
    ?>
    <?= $breadcrumbs->toHtml() ?>
<?php else: ?>
    <div class="breadcrumbs" aria-label="Breadcrumb" role="navigation"></div>
<?php endif; ?>
<?php if (!$config->isServerSideRendered() || $config->isClientSideOverrideAllowed()): ?>
    <?php $widget = $this->helper(Data::class)->jsonDecode($viewModel->getJsonConfigurationHtmlEscaped()); ?>
    <script type="text/x-magento-init">
        {
            ".breadcrumbs": {
                "breadcrumbs": <?= /* @noEscape */ $this->helper(Data::class)->jsonEncode($widget['breadcrumbs']) ?>
            }
        }
    </script>
<?php endif; ?>
