<?php
/**
 * Copyright © OpenGento, All rights reserved.
 * See LICENSE bundled with this library for license details.
 */
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\Escaper;
use Magento\Theme\Block\Html\Breadcrumbs as BreadcrumbsBlock;
use Opengento\ProductBreadcrumbs\ViewModel\Product\Breadcrumbs as BreadcrumbsConfig;

/** @var ViewModelRegistry $viewModels */
/** @var Escaper $escaper */
/** @var BreadcrumbsBlock $block */

/** @var BreadcrumbsConfig $config */
$config = $viewModels->require(BreadcrumbsConfig::class);
?>
<div id="product_breadcrumbs" aria-label="Breadcrumb" role="navigation" x-init="generateProductBreadcrumbsOnProductPage()">
<?php if ($config->isServerSideRendered()): ?>
    <?= $block->fetchView($block->getTemplateFile('Magento_Theme::html/breadcrumbs.phtml')) ?>
<?php endif; ?>
</div>
<script>
    function generateProductBreadcrumbsOnProductPage() {
<?php if (!$config->isServerSideRendered() || $config->isClientSideOverrideAllowed()): ?>
    <?php $breadcrumbsTemplate = '<div id="product_breadcrumbs" aria-label="Breadcrumb" role="navigation">' . $block->fetchView($block->getTemplateFile('Magento_Catalog::product/view/breadcrumbs.phtml')) . '</div>'; ?>
    hyva.replaceDomElement('#product_breadcrumbs', '<?= $escaper->escapeJs($breadcrumbsTemplate) ?>');
<?php endif; ?>
    }
</script>
